local_configs:
  server:
    port: 8080
    host: "localhost"

  database:
    host: "localhost"
    port: "5432"
    name: "postgres"
    user: "postgres"
    schema: "public"
    password: "postgres"

  jwt:
    audience: "itv_users"
    domain: "https://itv.uz"
    realm: "uz.itv"
    secret: "TheB3s7Pa$$w0rdlnth3hlst0ryEv3R"
    access_token_ttl: 1800
    refresh_token_ttl: 604800